# Generated by Django 5.2.9 on 2025-12-03 13:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('quizes', models.JSONField(blank=True, null=True)),
                ('pdf', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(default=0, help_text='0 - not completed, 1 - completed', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
