# Generated by Django 5.2.9 on 2025-12-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_remove_topic_quizes_alter_topic_pdf_quizquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='quiz_file',
            field=models.FileField(blank=True, help_text='Matn fayl (txt) formatida: savol, A) ..., B) ..., C) ..., D) ..., Javob: X', null=True, upload_to='quizzes/'),
        ),
    ]
